<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="8" name="Default test" tests="1" failures="1" timestamp="2023-11-15T02:23:45 PST" time="1.614" errors="0">
  <testcase name="deletemeterReadingvalidv4" time="1.54" classname="Private.MeterReadControllerV4">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.fail(Assert.java:100)
at Private.MeterReadControllerV4.deletemeterReadingvalidv4(MeterReadControllerV4.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- deletemeterReadingvalidv4 -->
  <testcase name="putMeterReadinginWorkV4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- putMeterReadinginWorkV4 -->
  <testcase name="PostMeterReadv4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- PostMeterReadv4 -->
  <testcase name="putMeterReadingNetMeterV4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- putMeterReadingNetMeterV4 -->
  <testcase name="deletemeterReadingErrorv4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- deletemeterReadingErrorv4 -->
  <testcase name="getmeterlastDocumentv4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- getmeterlastDocumentv4 -->
  <testcase name="getmeterReadingnextv4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- getmeterReadingnextv4 -->
  <testcase name="putMeterReadingnottheLatestreadingV4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- putMeterReadingnottheLatestreadingV4 -->
  <testcase name="postMeterReadPostInvalidv4" time="0.0" classname="Private.MeterReadControllerV4">
    <ignored/>
  </testcase> <!-- postMeterReadPostInvalidv4 -->
</testsuite> <!-- Default test -->
