<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="3" name="Default test" tests="1" failures="1" timestamp="2024-02-13T05:12:15 PST" time="1.705" errors="0">
  <testcase name="postingReceivable4Error" time="1.64" classname="Public.checkControllerv4">
    <failure type="java.lang.AssertionError" message="{&amp;quot;Check&amp;quot;:{&amp;quot;Success&amp;quot;:false,&amp;quot;Data&amp;quot;:{&amp;quot;DocumentNumber&amp;quot;:&amp;quot;CHEQ00000000009&amp;quot;,&amp;quot;Receivable&amp;quot;:[{&amp;quot;ChargeDocument&amp;quot;:&amp;quot;MISC00000000392&amp;quot;,&amp;quot;Posted&amp;quot;:false}],&amp;quot;PostingReport&amp;quot;:true,&amp;quot;PostingError&amp;quot;:true,&amp;quot;ReportList&amp;quot;:[{&amp;quot;Name&amp;quot;:&amp;quot;Post Check Refund Edit List&amp;quot;,&amp;quot;PrintOrder&amp;quot;:1}],&amp;quot;ReportErrorList&amp;quot;:[{&amp;quot;Name&amp;quot;:&amp;quot;Post Check Refund Error List&amp;quot;,&amp;quot;PrintOrder&amp;quot;:1}]},&amp;quot;Messages&amp;quot;:[{&amp;quot;Enabled&amp;quot;:1,&amp;quot;Info&amp;quot;:&amp;quot;Posting validation warning found. Refer to posting error report.&amp;quot;,&amp;quot;Level&amp;quot;:2},{&amp;quot;Enabled&amp;quot;:1,&amp;quot;Info&amp;quot;:&amp;quot;csmApi_spCheckPostingReceivableCreate - Cannot insert the value NULL into column &amp;apos;umTotalTaxes&amp;apos;, table &amp;apos;TWO.dbo.UTX&amp;apos;; column does not allow nulls. INSERT fails.&amp;quot;,&amp;quot;Level&amp;quot;:3}]}}">
      <![CDATA[java.lang.AssertionError: {"Check":{"Success":false,"Data":{"DocumentNumber":"CHEQ00000000009","Receivable":[{"ChargeDocument":"MISC00000000392","Posted":false}],"PostingReport":true,"PostingError":true,"ReportList":[{"Name":"Post Check Refund Edit List","PrintOrder":1}],"ReportErrorList":[{"Name":"Post Check Refund Error List","PrintOrder":1}]},"Messages":[{"Enabled":1,"Info":"Posting validation warning found. Refer to posting error report.","Level":2},{"Enabled":1,"Info":"csmApi_spCheckPostingReceivableCreate - Cannot insert the value NULL into column 'umTotalTaxes', table 'TWO.dbo.UTX'; column does not allow nulls. INSERT fails.","Level":3}]}}
at org.testng.Assert.fail(Assert.java:99)
at Public.checkControllerv4.postingReceivable4Error(checkControllerv4.java:164)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postingReceivable4Error -->
  <testcase name="postingReceivable4RefundError" time="0.0" classname="Public.checkControllerv4">
    <ignored/>
  </testcase> <!-- postingReceivable4RefundError -->
  <testcase name="PostCheckv4" time="0.0" classname="Public.checkControllerv4">
    <ignored/>
  </testcase> <!-- PostCheckv4 -->
  <testcase name="putChecksendtoAPv4" time="0.0" classname="Public.checkControllerv4">
    <ignored/>
  </testcase> <!-- putChecksendtoAPv4 -->
</testsuite> <!-- Default test -->
