<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RND-BASE-A" ignored="9" name="Default test" tests="1" failures="1" timestamp="2023-03-09T04:49:41 PST" time="3.729" errors="0">
  <testcase name="postcreateServiceOrder_v3" time="3.559" classname="Public.ServiceOrderControllerV3">
    <failure type="java.lang.AssertionError" message="Service Order not created">
      <![CDATA[java.lang.AssertionError: Service Order not created
at org.testng.Assert.fail(Assert.java:99)
at Public.ServiceOrderControllerV3.postcreateServiceOrder_v3(ServiceOrderControllerV3.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- postcreateServiceOrder_v3 -->
  <testcase name="putTaskCompleteNocharge_v3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putTaskCompleteNocharge_v3 -->
  <testcase name="putaddMeterReading_v_3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putaddMeterReading_v_3 -->
  <testcase name="putaddMiscCharge_v_3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putaddMiscCharge_v_3 -->
  <testcase name="putTaskComplete_v_3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putTaskComplete_v_3 -->
  <testcase name="getServiceOrderRequestDetailsbyOptional_v3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- getServiceOrderRequestDetailsbyOptional_v3 -->
  <testcase name="putupdatecomment_v_3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putupdatecomment_v_3 -->
  <testcase name="getServiceOrderRequestDetails_v3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- getServiceOrderRequestDetails_v3 -->
  <testcase name="putswitchMeter_v_3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- putswitchMeter_v_3 -->
  <testcase name="getServiceOrder_v3" time="0.0" classname="Public.ServiceOrderControllerV3">
    <ignored/>
  </testcase> <!-- getServiceOrder_v3 -->
</testsuite> <!-- Default test -->
